namespace: dev
track: staging
replicaCount: 1
deploymentUrl: "publish.dev.buffer.com"
ingress:
  enabled: true
  path: /
  annotations:
    kubernetes.io/ingress.class: nginx
env:
  - name: AUTH_SVC_ADDR
    value: http://authentication-service.core
  - name: API_ADDR
    value: http://publish-api-dev.dev:443
  - name: DD_AGENT_HOST
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: DD_SERVICE_NAME
    value: "publish-server"
  - name: DD_RUM_APP_ID
    valueFrom:
      secretKeyRef:
        key: dd-rum-app-id
        name: buffer-publish-keys
  - name: DD_RUM_CLIENT_TOKEN
    valueFrom:
      secretKeyRef:
        key: dd-rum-client-token
        name: buffer-publish-keys
  - name: LOG_LEVEL
    value: NOTICE
  - name: ANALYZE_API_ADDR
    value: http://analyze-api-dev.dev:443
  - name: BUGSNAG_KEY
    valueFrom:
      secretKeyRef:
        key: bugsnag
        name: buffer-publish-keys
  - name: PUSHER_APP_ID
    valueFrom:
      secretKeyRef:
        key: pusher-app-id
        name: buffer-publish-keys
  - name: PUSHER_APP_KEY
    valueFrom:
      secretKeyRef:
        key: pusher-app-key
        name: buffer-publish-keys
  - name: PUSHER_APP_SECRET
    valueFrom:
      secretKeyRef:
        key: pusher-app-secret
        name: buffer-publish-keys
  - name: PUSHER_CLUSTER
    valueFrom:
      secretKeyRef:
        key: pusher-cluster
        name: buffer-publish-keys
  - name: STRIPE_PUBLISHABLE
    valueFrom:
      secretKeyRef:
        key: stripe-publishable
        name: buffer-publish-keys
  - name: RELEASE_STAGE
    value: staging
  - name: CLIENT_ID
    valueFrom:
      secretKeyRef:
        key: client-id
        name: buffer-publish-keys
  - name: CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        key: client-secret
        name: buffer-publish-keys
